[package]
name = "jobqu_examples_memory"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
jobqu = { path = "../../jobqu", features = ["memory"] }
tokio = { version = "1.41", features = [] }
